[project]
name = "fbpyutils_ai"
version = "0.1.0"
description = "Francisco Bispo's Utils for AI"
authors = [
    { name = "Francisco C J Bispo", email = "fcjbispo@franciscobispo.net" },
]
requires-python = ">=3.10,<=3.13"
dependencies = [
    "mcp[cli]>=1.2.1",
    "requests",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
